import matplotlib.pyplot as plt
import math


if __name__ == '__main__':
	f = open('load test')
	file_details = f.readlines()
	f.close()
	output_power=file_details[1].split(',')
	voltage=file_details[3].split(',')
	current=file_details[5].split(',')
	speed=file_details[7].split(',')
	torque=file_details[9].split(',')
	slip=file_details[11].split(',')
	pf=file_details[13].split(',')
	eff=file_details[15].split(',')
	plt.plot(output_power,voltage)
	plt.xlabel('Output power')
	plt.ylabel('Voltage')
	plt.suptitle('Output power vs voltage')
	plt.legend()
	plt.show()
	plt.plot(output_power,current)
	plt.xlabel('Output power')
	plt.ylabel('Current')
	plt.suptitle('Output power vs current')
	plt.legend()
	plt.show()
	plt.plot(output_power,speed)
	plt.xlabel('Output power')
	plt.ylabel('Speed')
	plt.suptitle('Output power vs speed')
	plt.legend()
	plt.show()
	plt.plot(output_power,torque)
	plt.xlabel('Output power')
	plt.ylabel('Torque')
	plt.suptitle('Output power vs torque')
	plt.legend()
	plt.show()
	plt.plot(output_power,slip)
	plt.xlabel('Output power')
	plt.ylabel('slip')
	plt.suptitle('Output power vs slip')
	plt.legend()
	plt.show()
	plt.plot(output_power,pf)
	plt.xlabel('Output power')
	plt.ylabel('Power factor')
	plt.suptitle('Output power vs power factor')
	plt.legend()
	plt.show()
	plt.plot(output_power,eff)
	plt.xlabel('Output power')
	plt.ylabel('Efficiency')
	plt.suptitle('Output power vs efficiency')
	plt.legend()
	plt.show()
	